### ISSUE TITLE
Is it compatible with Magento 1.9.1(latest version)?

### ISSUE THREAD

**Issue by ManasN** [payu-india/PayU-Magento#1]
Sorry to put it in issues, but I found no other ways to get a reply from devs directly. I am about to use payU India in our next upcoming ecommerce project. Thank you.

**Comment by epicwhale** [comment]
Yes, it will work smoothly on Magento 1.9.1

**Comment by ManasN** [comment]
Thanks :)

**Comment by sudhirs1** [comment]
Could someone please re confirm if this PayU module is compatible with Magento 1.9.1(latest version)???
